# docker-compose.yml

# for raspi

version: "3"
services:
  loki:
    image: grafana/loki:2.9.6
    volumes:
      - /home/zspekt/.services/logging/raspi/loki:/etc/loki # config
      - /home/zspekt/logging/loki:/tmp/loki
    ports:
      - "3100:3100"
    restart: always
    command: -config.file=/etc/loki/loki.yaml
  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /home/zspekt/openWrtLogs:/var/log/openWrt
      - /var/log:/var/log # system logs
      - /home/zspekt/.services/logging/raspi/promtail:/etc/promtail # config
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: always
    command: -config.file=/etc/promtail/promtail.yaml
