# docker-compose.yml

# for desktop

version: "3"
services:
  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log # system logs
      - /home/zspekt/.services/logging/desktop/promtail:/etc/promtail # config
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: always
    command: -config.file=/etc/promtail/promtail.yaml

    networks:
      - bridge

networks:
  bridge:
    driver: bridge
